services:
  qdrant:
    image: qdrant/qdrant:dev
    restart: always
    container_name: qdrant_container
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333 # HTTP
      - 6334 # gRPC
      - 6335 # Distributed deployment
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO
